default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'db' %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ntms_development

test:
  <<: *default
  database: ntms_test

production:
  <<: *default
  url: <%= ENV["RDS_DATABASE_URL"] %>